class AppStrings {
  // Language codes
  static const String defaultLanguage = 'en';
  
  // Static translations map
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'KarmaShop',
      'welcome': 'Welcome',
      'search': 'Search',
      'profile': 'Profile',
      'orders': 'Orders',
      'wishlist': 'Wishlist',
      'cart': 'Cart',
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'add_to_cart': 'Add to Cart',
      'added_to_cart': 'Added to Cart',
      'add_to_wishlist': 'Add to Wishlist',
      'added_to_wishlist': 'Added to Wishlist',
      'removed_from_wishlist': 'Removed from Wishlist',
      'select_language': 'Select Language',
      'current_language': 'Current Language',
      'search_languages': 'Search Languages',
      'indian_languages': 'Indian Languages',
      'other_languages': 'Other Languages',
      'no_languages_found': 'No Languages Found',
      'language_changed': 'Language Changed to',
      'find_what_you_need': 'Find What You Need',
      'categories': 'Categories',
      'no_categories_available': 'No Categories Available',
      'featured_products': 'Featured Products',
      'successfully_logged_out': 'Successfully Logged Out',
      'logout_error': 'Logout Error',
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'sign_in_to_continue': 'Sign in to Continue',
      'join_karma_shop': 'Join KarmaShop',
      'name': 'Name',
      'products_found': 'products found',
      'clear_filter': 'Clear Filter',
      'no_products_found': 'No Products Found',
      'no_products_in_category': 'No products found in category',
      'browse_all_products': 'Browse All Products',
      'search_products': 'Search Products',
      'search_in_category': 'Search in this category',
      'cancel': 'Cancel',
    },
    'hi': {
      'app_name': 'कर्मा शॉप',
      'welcome': 'स्वागत',
      'search': 'खोजें',
      'profile': 'प्रोफ़ाइल',
      'orders': 'ऑर्डर',
      'wishlist': 'विशलिस्ट',
      'cart': 'कार्ट',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'dark_mode': 'डार्क मोड',
      'logout': 'लॉगआउट',
      'login': 'लॉगिन',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'add_to_cart': 'कार्ट में जोड़ें',
      'added_to_cart': 'कार्ट में जोड़ा गया',
      'add_to_wishlist': 'विशलिस्ट में जोड़ें',
      'added_to_wishlist': 'विशलिस्ट में जोड़ा गया',
      'removed_from_wishlist': 'विशलिस्ट से हटाया गया',
      'select_language': 'भाषा चुनें',
      'current_language': 'वर्तमान भाषा',
      'search_languages': 'भाषाएं खोजें',
      'indian_languages': 'भारतीय भाषाएं',
      'other_languages': 'अन्य भाषाएं',
      'no_languages_found': 'कोई भाषा नहीं मिली',
      'language_changed': 'भाषा बदली गई',
      'find_what_you_need': 'जो चाहिए वो खोजें',
      'categories': 'श्रेणियां',
      'no_categories_available': 'कोई श्रेणी उपलब्ध नहीं',
      'featured_products': 'फीचर्ड उत्पाद',
      'successfully_logged_out': 'सफलतापूर्वक लॉगआउट',
      'logout_error': 'लॉगआउट त्रुटि',
      'welcome_back': 'वापस स्वागत',
      'create_account': 'खाता बनाएं',
      'sign_in_to_continue': 'जारी रखने के लिए साइन इन करें',
      'join_karma_shop': 'कर्मा शॉप में शामिल हों',
      'name': 'नाम',
      'products_found': 'उत्पाद मिले',
      'clear_filter': 'फिल्टर साफ करें',
      'no_products_found': 'कोई उत्पाद नहीं मिला',
      'no_products_in_category': 'इस श्रेणी में कोई उत्पाद नहीं मिला',
      'browse_all_products': 'सभी उत्पाद देखें',
      'search_products': 'उत्पाद खोजें',
      'search_in_category': 'इस श्रेणी में खोजें',
      'cancel': 'रद्द करें',
    },
    'bn': {
      'app_name': 'কর্মা শপ',
      'welcome': 'স্বাগতম',
      'search': 'খুঁজুন',
      'profile': 'প্রোফাইল',
      'orders': 'অর্ডার',
      'wishlist': 'পছন্দের তালিকা',
      'cart': 'কার্ট',
      'settings': 'সেটিংস',
      'language': 'ভাষা',
      'dark_mode': 'ডার্ক মোড',
      'logout': 'লগআউট',
      'login': 'লগইন',
      'email': 'ইমেইল',
      'password': 'পাসওয়ার্ড',
      'add_to_cart': 'কার্টে যোগ করুন',
      'added_to_cart': 'কার্টে যোগ করা হয়েছে',
      'add_to_wishlist': 'পছন্দের তালিকায় যোগ করুন',
      'added_to_wishlist': 'পছন্দের তালিকায় যোগ করা হয়েছে',
      'removed_from_wishlist': 'পছন্দের তালিকা থেকে সরানো হয়েছে',
      'select_language': 'ভাষা নির্বাচন করুন',
      'current_language': 'বর্তমান ভাষা',
      'search_languages': 'ভাষা খুঁজুন',
      'indian_languages': 'ভারতীয় ভাষা',
      'other_languages': 'অন্যান্য ভাষা',
      'no_languages_found': 'কোন ভাষা পাওয়া যায়নি',
      'language_changed': 'ভাষা পরিবর্তিত হয়েছে',
      'find_what_you_need': 'আপনার প্রয়োজনীয় জিনিস খুঁজুন',
      'categories': 'বিভাগ',
      'no_categories_available': 'কোন বিভাগ উপলব্ধ নেই',
      'featured_products': 'বৈশিষ্ট্যযুক্ত পণ্য',
      'successfully_logged_out': 'সফলভাবে লগআউট',
      'logout_error': 'লগআউট ত্রুটি',
      'welcome_back': 'আবার স্বাগতম',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'sign_in_to_continue': 'চালিয়ে যেতে সাইন ইন করুন',
      'join_karma_shop': 'কর্মা শপে যোগ দিন',
      'name': 'নাম',
      'products_found': 'পণ্য পাওয়া গেছে',
      'clear_filter': 'ফিল্টার সাফ করুন',
      'no_products_found': 'কোন পণ্য পাওয়া যায়নি',
      'no_products_in_category': 'এই বিভাগে কোন পণ্য পাওয়া যায়নি',
      'browse_all_products': 'সব পণ্য দেখুন',
      'search_products': 'পণ্য খুঁজুন',
      'search_in_category': 'এই বিভাগে খুঁজুন',
      'cancel': 'বাতিল',
    },
    'ta': {
      'app_name': 'கர்மா ஷாப்',
      'welcome': 'வரவேற்கிறோம்',
      'search': 'தேடுங்கள்',
      'profile': 'சுயவிவரம்',
      'orders': 'ஆர்டர்கள்',
      'wishlist': 'விருப்பப்பட்டியல்',
      'cart': 'கார்ட்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'dark_mode': 'டார்க் மோட்',
      'logout': 'வெளியேறு',
      'login': 'உள்நுழை',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'add_to_cart': 'கார்ட்டில் சேர்க்கவும்',
      'added_to_cart': 'கார்ட்டில் சேர்க்கப்பட்டது',
      'add_to_wishlist': 'விருப்பப்பட்டியலில் சேர்க்கவும்',
      'added_to_wishlist': 'விருப்பப்பட்டியலில் சேர்க்கப்பட்டது',
      'removed_from_wishlist': 'விருப்பப்பட்டியலில் இருந்து அகற்றப்பட்டது',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'current_language': 'தற்போதைய மொழி',
      'search_languages': 'மொழிகளைத் தேடுங்கள்',
      'indian_languages': 'இந்திய மொழிகள்',
      'other_languages': 'பிற மொழிகள்',
      'no_languages_found': 'மொழிகள் எதுவும் கிடைக்கவில்லை',
      'language_changed': 'மொழி மாற்றப்பட்டது',
      'find_what_you_need': 'உங்களுக்குத் தேவையானதைக் கண்டறியுங்கள்',
      'categories': 'வகைகள்',
      'no_categories_available': 'வகைகள் எதுவும் கிடைக்கவில்லை',
      'featured_products': 'சிறப்பு தயாரிப்புகள்',
      'successfully_logged_out': 'வெற்றிகரமாக வெளியேறப்பட்டது',
      'logout_error': 'வெளியேறும் பிழை',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'create_account': 'கணக்கை உருவாக்கவும்',
      'sign_in_to_continue': 'தொடர உள்நுழையவும்',
      'join_karma_shop': 'கர்மா ஷாப்பில் சேரவும்',
      'name': 'பெயர்',
      'products_found': 'தயாரிப்புகள் கிடைத்தன',
      'clear_filter': 'வடிப்பானை அழிக்கவும்',
      'no_products_found': 'தயாரிப்புகள் எதுவும் கிடைக்கவில்லை',
      'no_products_in_category': 'இந்த வகையில் தயாரிப்புகள் எதுவும் கிடைக்கவில்லை',
      'browse_all_products': 'அனைத்து தயாரிப்புகளையும் பார்க்கவும்',
      'search_products': 'தயாரிப்புகளைத் தேடுங்கள்',
      'search_in_category': 'இந்த வகையில் தேடுங்கள்',
      'cancel': 'ரத்து செய்',
    },
  };

  // Get translation for a key in the current language
  static String get(String key, String languageCode) {
    final languageMap = translations[languageCode] ?? translations[defaultLanguage]!;
    return languageMap[key] ?? translations[defaultLanguage]![key] ?? key;
  }
}